from app.schemas.state import AnalysisState
from app.schemas.models import RiskCard

def run_technical_risk(state: AnalysisState) -> list[dict]:
    risks = [
        RiskCard(risk_id="battery-identification", stage="Product Design", module="Battery identification", risk="AA, AAA and 14500 identification may overlap across state-of-charge, brands and temperature.", cause="Voltage and dimensional overlap", trigger="Unverified boundary conditions", impact="Wrong mode or output selection", severity=5, probability=None, detectability=3, evidence_ids=["ev-project-brief"], validation_method="Risk-based tests across configuration × brand × SOC × temperature × operating mode", mitigation="Use conservative identification thresholds and a validation matrix", status="NEED_VERIFY"),
        RiskCard(risk_id="boost-stability", stage="EVT", module="BOOST driver", risk="Output stability and efficiency may vary with input voltage.", cause="Wide input range", trigger="Battery configuration change", impact="Performance inconsistency or thermal load", severity=4, probability=None, detectability=3, evidence_ids=["ev-project-brief"], validation_method="Measure Vin, Iin, Vout, Iout, efficiency and temperature by configuration", mitigation="Define derating and control limits after bench validation", status="NEED_VERIFY"),
        RiskCard(risk_id="thermal-14500", stage="DVT", module="Thermal management", risk="14500 operation is a potential thermal risk.", cause="Higher energy input", trigger="Continuous high-mode use", impact="Comfort, safety and reliability concerns", severity=5, probability=None, detectability=2, evidence_ids=["ev-project-brief"], validation_method="Test at 30 s, 1 min, 3 min, 5 min and 10 min against project-defined thresholds", mitigation="Thermal step-down after thresholds are defined", status="NEED_VERIFY"),
        RiskCard(risk_id="mechanical-tolerance", stage="PVT", module="Mechanical compensation", risk="Battery length and diameter tolerance can reduce contact consistency.", cause="Cell variation, spring compression and tolerance stack-up", trigger="Drop, vibration or wear", impact="Intermittent power", severity=4, probability=None, detectability=3, evidence_ids=["ev-project-brief"], validation_method="Extreme-size fixture, drop, vibration and contact-resistance tests", mitigation="Validate spring force and contact geometry with limit gauges", status="NEED_VERIFY")
    ]
    return [risk.model_dump() | {"risk_score": risk.risk_score} for risk in risks]
